Apps/Controlador/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = "Controlador"

urlpatterns = [
    
    path('', DashboardView.as_view(),name='dashboard'),

    ##### Mulas #####
    path('Lista_Mulas', ListaMulaView.as_view(),name='lista_de_mulas'),
    path('Editar_Mula/<str:pk>', EditarMulaView.as_view(),name='editar_mula'),
    path('Detail_Mula/<str:pk>', DetailMula.as_view(),name='detalles_mula'),

    ##### Objeto #####
    path('Lista_Objetos', ListaObjetosView.as_view(),name='lista_de_objetos'),
    

    ##### Gasto Extra #####
    path('Lista_Gastos_Extras', ListaGastosExtrasView.as_view(),name='lista_gastos_extra'),
    path('Crear_Gasto_Extra', CrearGastoExtraeView.as_view(),name='crear_gasto_extra'),

    ##### Envios #####
    path('Lista_Envios', ListaEnvioView.as_view(),name='lista_de_envios'),
    path('Crear_Envio', CrearEnvioView.as_view(),name='crear_envio'),
    path('Detail_Envio/<str:pk>', DetailEnvioView.as_view(),name='detalles_envio'),
    path('Editar_Envio/<str:pk>', EditarEnvioView.as_view(),name='editar_envio')
    
    #path('Prueba/', ArticleView.as_view(),name='prueba'),
]

Mula/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Apps.Controlador.urls')),


]

Apps/Controlador/models.py
from django.db import models
import uuid
# Create your models here.




class Mula(models.Model):
    token = models.UUIDField(primary_key=True,editable=False,blank=True) 
    Nombre = models.CharField(max_length=30)
    Telefono = models.IntegerField(null=True,blank=True)
    CantidadDeEnviosRealizados = models.IntegerField(null=True,blank=True,default=0)

    def __str__(self):
        return self.Nombre
    
    def save(self,*args,**kwargs):
        if self.pk is None:
            self.token = uuid.uuid4()
        super().save(*args,**kwargs)

 
class Objeto(models.Model):

    
    token = models.UUIDField(primary_key=True,editable=False,blank=True) 
    Nombre = models.CharField(max_length=30)
    PrecioDeCompra = models.FloatField(null=True,blank=True,default=0)
    PrecioDeVenta = models.FloatField(null=True,blank=True,default=0)

    def __str__(self):
        return self.Nombre

    def save(self,*args,**kwargs):
        if self.pk is None:
            self.token = uuid.uuid4()
        super().save(*args,**kwargs)

class Gasto_Extra(models.Model):

    
    token = models.UUIDField(primary_key=True,editable=False,blank=True) 
    Nombre = models.CharField(max_length=30)
    Cantidad_de_dinero = models.FloatField(null=True,blank=True,default=0)
    notas = models.TextField(null=True,blank=True,max_length=99999)

    def __str__(self):
        return self.Nombre

    def save(self,*args,**kwargs):
        if self.pk is None:
            self.token = uuid.uuid4()
        super().save(*args,**kwargs)


class Inventario(models.Model):

    token = models.UUIDField(primary_key=True,editable=False,blank=True) 
    

    def save(self,*args,**kwargs):
        if self.pk is None:
            self.token = uuid.uuid4()
        super().save(*args,**kwargs)


class Pack(models.Model):

    
    token = models.UUIDField(primary_key=True,editable=False,blank=True) 
    objeto=models.ForeignKey(Objeto,on_delete=models.CASCADE)
    Cantidad_de_ejemplares = models.PositiveBigIntegerField(null=True,blank=True,default=0)
    Inventario =  models.ForeignKey(Inventario,on_delete=models.CASCADE)



    def save(self,*args,**kwargs):
        if self.pk is None:
            self.token = uuid.uuid4()
        super().save(*args,**kwargs)





class Envio(models.Model):

    
    token = models.UUIDField(primary_key=True,editable=False,blank=True) 
    Nombre = models.CharField(max_length=30)
    Inventario =  models.ForeignKey(Inventario,blank=True,null=True,on_delete=models.SET_NULL)

    Mula =  models.ForeignKey(Mula,blank=True,null=True,on_delete=models.SET_NULL)

    Gastos_extras =  models.ManyToManyField(Gasto_Extra)
    Gasto_total_en_pasajes= models.FloatField(null=True,blank=True,default=0)
    Dinero_Total_obtenido = models.FloatField(null=True,blank=True,default=0)
    Dinero_Total_Invertido = models.FloatField(null=True,blank=True,default=0)
    Ganancia = models.FloatField(null=True,blank=True,default=0)
    notas = models.TextField(null=True,blank=True,max_length=99999)
    Fecha = models.DateField(null=True,blank=True)
    


    def __str__(self):
        return self.Nombre

    def save(self,*args,**kwargs):
        if self.pk is None:
            self.token = uuid.uuid4()
        super().save(*args,**kwargs)

Apps/Controlador/views.py
from django.views.generic import TemplateView,FormView,ListView,CreateView,DeleteView,DetailView
from .models import *
from .forms import *
from django.http import JsonResponse
from django.views.decorators.csrf  import csrf_exempt
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls  import reverse_lazy
from django.shortcuts import render,redirect
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
#funcion para obtener los packs de un envio
def getPacks(envio):
    data=[]

    inventario = envio.Inventario
                
    for i in Pack.objects.filter(Inventario=inventario):
        data.append(i)
    
    return data


#Funcion para eliminar una o varias mulas
def DeleteMulaFunction(data):

    datos_for_return =[]
    datos=[]
    #conviertes la data en una lista(ya que al venir esa data de un objeto json por ajax viene como str y hay que convertirla con el metodo split)
    lista= data.split(',')
    
    #Analizamos que la lista tenga algo, en caso de tenerlo lo eliminamos    
    if len(data) == 0:
        pass 
    else:
        for i in lista:
            mula = Mula.objects.get(pk=i)
            envios = Envio.objects.filter(Mula=mula)
            
            if envios:
                for k in envios:
                    datos.append(k)
            else:
                mula.delete()
            
            if datos:
                datos_for_return.append({'mula':mula.Nombre,'envios':datos})
                datos=[]
        
        return datos_for_return

    
    
#Funcion para eliminar uno o varios envios
def DeleteEnvioFunction(data):

    #conviertes la data en una lista(ya que al venir esa data de un objeto json por ajax viene como str y hay que convertirla con el metodo split)
    lista= data.split(',')
    
    #Analizamos que la lista tenga algo, en caso de tenerlo lo eliminamos    
    if len(data) == 0:
        pass 
    else:
        for i in lista:
            
            envio = Envio.objects.get(pk=i)
            
            inventario = Inventario.objects.get(pk=envio.Inventario.token)

            RestaroSumarViajeALaMula(False,envio.Mula)

        
            envio.delete()


            #eliminando el inventario asociado al envio
            inventario.delete()
            

#Funcion para eliminar uno o varios objetos
def DeleteObjetoFunction(data):

    #conviertes la data en una lista(ya que al venir esa data de un objeto json por ajax viene como str y hay que convertirla con el metodo split)
    lista= data.split(',')
    
    datos=[]
    datos_for_return=[]
    #Analizamos que la lista tenga algo, en caso de tenerlo lo eliminamos    
    if len(data) == 0:
        pass 
    else:
        for i in lista:
            
            #En este ciclo analizamos que los objetos que fueron seleccionados para eliminar no esten asociados a ningun envio
            #Si estan asociados a alguno pues no eliminamos y lo informamos para que el usuario tome las acciones pertinentes 
            obj = Objeto.objects.get(pk=i)
            
            pack = Pack.objects.filter(objeto=obj)

            

            for k in pack:
                x = Envio.objects.get(Inventario=k.Inventario)
                datos.append(x)
            
            if datos:
                datos_for_return.append({'objeto':obj.Nombre,'envios':datos})
                datos=[]
            else:
                obj.delete()
                

        
            if datos_for_return:
              
                return datos_for_return
                
  
            else:
                return False




def RestaroSumarViajeALaMula(restar_o_sumar,mula):
    mula = mula
    if restar_o_sumar:
        
        mula.CantidadDeEnviosRealizados += 1
        
    else:
        mula.CantidadDeEnviosRealizados -= 1
    
    mula.save()

    



def procesar_datos(data,tipo,estado):
    
    data_return=[]
    #Aqui los meto dentro de una lista de python especificando que donde quiera que vea un ' ,' es un elemento nuevo
    #El espacio antes de la coma es porque como son diccionarios puede haber muchas comas 
    #entonces configure que me enviara los elementos con un espaciado por medio para poder identificar 
    #que , es la de dentro de un diccionario y que , es la que divide un elemento de otro
    lista= data.split(' ,')
    listaDict=[]

    #Aqui convierto los diccionarios que vienen en str en dicts de python para poder acceder a sus datos
    for j in lista:
        listaDict.append(json.loads(j))



        #si estado == true hacemos referencia que estamos cerrando el registro (de inventario o gastos extras)
        #si estado == false hacemos referencia que estamos abriendo el registro (de inventario o gastos extras)

        # si tipo == true hacemos referencia al trabajo con el inventario
        # si tipo == false hacemos referencia al trabajo con los gastos extras


    if estado:


        #ESTADO = TRUE TIPO = TRUE, CERRANDO INVENTARIO
        if tipo:
            for j in listaDict:
                for i in Objeto.objects.filter(token = j["token"]).values():
                    i['cantidad']=j["cantidad"]
                    i['listo']=True
                    #Pack.objects.create(objeto_id=i['token'],Cantidad_de_ejemplares=i['cantidad'])
                    data_return.append(i)
        
        #ESTADO = TRUE TIPO = FALSE, CERRANDO GASTOS EXTRAS
        else:

            for j in listaDict:
                for i in Gasto_Extra.objects.filter(token = j["token"]).values():
                    i['listo']=True
                    data_return.append(i)
    

    else:

        #ESTADO = FALSE TIPO = TRUE, ABRIENDO INVENTARIO    
        if tipo:

                datos_que_se_encontraban_seleccionados=[]

                for j in listaDict:
                    for i in Objeto.objects.filter(token = j["token"]).values():
                            i['cantidad']=j["cantidad"]
                            i['listo']=False
                            datos_que_se_encontraban_seleccionados.append(i)


                

                todos=[]
                for i in Objeto.objects.all().values():
                    todos.append(i)

                
                for i in todos:
                    for k in datos_que_se_encontraban_seleccionados:
                        if i["token"]==k["token"]:                                                       
                            i['cantidad']=k["cantidad"]
                            i['listo']=False

                data_return=todos
        
        #ESTADO = FALSE TIPO = FALSE, ABRIENDO GASTOS EXTRAS
        else:

            datos_que_se_encontraban_seleccionados=[]

            for j in listaDict:
                for i in Gasto_Extra.objects.filter(token = j["token"]).values():
                        i['cantidad']=j["cantidad"]
                        i['listo']=False
                        datos_que_se_encontraban_seleccionados.append(i)


            

            todos=[]
            for i in Gasto_Extra.objects.all().values():
                todos.append(i)

            
            for i in todos:
                for k in datos_que_se_encontraban_seleccionados:
                    if i["token"]==k["token"]:                                                       
                        i['cantidad']='0'
                        i['listo']=False

            data_return=todos



    return data_return





#Vista Index
class IndexdView (TemplateView):
    template_name= 'Controlador/index.html'


#Vista principal
class DashboardView (TemplateView):
    template_name= 'Controlador/dashboard.html' 

    def get_dinero_mensual(self):
        data=[]
        suma_total=0
        year = datetime.now().year

        for m in range(1,13):
            total = Envio.objects.filter(Fecha__year=year,Fecha__month=m)
            data.append(total)
       
        
        for i in range(0,len(data)):
            if data[i]:
                for k in data[i]:
                    suma_total += k.Ganancia
                data[i]= suma_total
                suma_total=0

            else:
                data[i]=0
            

        return data

    def get_cantidad_total_de_envios(self):
        datos = Envio.objects.all()
        data = len(datos)
        return data

    def get_cantidad_total_de_mulas(self):
        datos = Mula.objects.all()
        data = len(datos)
        return data

    def get_cantidad_total_de_ganancia(self):
        datos = Envio.objects.all()
        ganancia_total =0
        if datos:
            for i in datos:
                ganancia_total += i.Ganancia
      
        return ganancia_total

    def get_cantidad_total_de_inversion(self):
        datos = Envio.objects.all()
        inversion_total =0
        if datos:
            for i in datos:
                inversion_total += i.Dinero_Total_Invertido
      
        return inversion_total

            


    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['x']=self.get_dinero_mensual()
        context['cant_envios']=self.get_cantidad_total_de_envios()
        context['cant_mulas']=self.get_cantidad_total_de_mulas()
        context['cant_ganancia']=self.get_cantidad_total_de_ganancia()
        context['cant_invertida']=self.get_cantidad_total_de_inversion()
        
        return context














####### MULAS #######

#Vista que muestra nuestra lista de mulas y las opciones correspondientes con estas
class ListaMulaView (ListView):
    template_name= 'Controlador/Mulas/lista_mulas.html'  
    model = Mula
    context_object_name="lista_mulas"

    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['form']=MulaForm()
        return context

Apps/Controlador/templates/Controlador/Envios/crear_envio.html
{% extends 'Controlador/base.html'%}

{% load static %}  
  

{% block contentPrincipal%}
<style>

  
  .inventario_listo{
    color: white !important;
    background-color: darkslategray !important;
  }

  .inventario_listo input{
    pointer-events: none;
  } 



  
  
  
  </style>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
       
      </div>
    </div><!-- /.container-fluid -->
  </section>

 <!-- Main content -->
 <section class="content">

    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <!-- Default box -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Crear Envio</h3>
            </div>
            <div class="card-body" style="display: block;">
              
                <form method="post" id="form">
                    {% csrf_token %}
              
                      
                  


                    <div class="form-group">
                        <span>Nombre:</span>
                        {{form.Nombre}}
                    </div>
            

                    <div class="form-group mt-4" id="packs">
                        <label>Inventario</label>
                        <table id="listado_de_objetos" class="hover cell-border" style="width:100%">

                            <thead>
                
                                <tr>
                                    <th scope="col" style="width: 1%; "><input rel='seleccionar_todo' id="selc_todo_invent" type='checkbox'/></th>
                                    <th scope="col" style="width: 35%; ">Nombre</th>
                                    <th scope="col" style="width: 25%; ">Precio de Compra</th>
                                    <th scope="col" style="width: 25%; ">Precio de venta</th>
                                    <th scope="col" style="width: 14%; ">Cantidad</th>
                                </tr>
                            </thead>
                
                        </table>
                        <spam id="contador_de_objetos">Objetos Seleccionados: 0</spam>
                        <button id="inventario_listo" class="btn btn-primary mr-5" style="width: 120px;">Listo!</button>
                        <button id="inventario_incompleto" class="btn btn-danger mr-5" style="width: 120px;display:none">Volver</button>

                        <div class="m-5">
                          <p id="parrafo_error" class="alert alert-danger" style="display:none"> Hay un objeto seleccionado sin definir la cantidad, recuerda que esta tiene que ser mayor que 0 </p>
                        </div>
                    </div>

            
                    <div class="form-group mt-4" id="gasto_extra">
                        

                        <label>Gastos Extras</label>
                        <table id="gastos_extras" class="hover cell-border" style="width:100%">

                            <thead>
                
                                <tr>
                                    <th scope="col" style="width: 1%; "><input rel='seleccionar_todo' id="selc_todo_gast_ext" type='checkbox'/></th>
                                    <th scope="col" style="width: 35%; ">Nombre</th>
                                    <th scope="col" style="width: 25%; ">Cantidad</th>
                                    <th scope="col" style="width: 25%; ">Detalles</th>
                                </tr>
                            </thead>
                
                        </table>
                        <spam id="contador_de_gastos">Gastos Seleccionados: 0</spam>
                        <button id="gastos_extras_listo" class="btn btn-primary mr-5" style="width: 120px;">Listo!</button>
                        <button id="gastos_extras_incompletos" class="btn btn-danger mr-5" style="width: 120px;display:none">Volver</button>

                        <div class="m-5">
                          <p id="parrafo_error" class="alert alert-danger" style="display:none"> Hay un objeto seleccionado sin definir la cantidad, recuerda que esta tiene que ser mayor que 0 </p>
                        </div>

                    </div>

                    <div class="form-group">
                      <span>Fecha:</span>
                      <input type="date" name="Fecha" placeholder="" autocomplete="off" class="form-control" id="id_Fecha">
                    </div>

                    <div class="form-group">
                      <span> Gasto total en pasajes:</span>
                      <input type="number" name="Gasto_total_en_pasajes" value="0" placeholder="" autocomplete="off" step="any" class="form-control" id="id_Gasto_total_en_pasajes">
                    </div>


                    <div class="form-group">
                      <span> Dinero total Invertido:</span>
                      <input type="number" name="Dinero_Total_Invertido" value="0" readonly placeholder="" autocomplete="off" step="any" class="form-control" id="id_Dinero_Total_Invertido"> 
                    </div>


                    <div class="form-group">
                      <span> Dinero total Obtenido:</span>
                      <input type="number" name="Dinero_Total_obtenido" readonly value="0" placeholder="" autocomplete="off" step="any" class="form-control" id="id_Dinero_Total_obtenido">
                        
                    </div>

                    <div class="form-group">
                      <span> Ganancia:</span>
                      <input type="number" name="Ganancia" value="0" readonly placeholder="" autocomplete="off" step="any" class="form-control" id="id_Ganancia">
                    </div>


                    <div class="form-group">
                      <p> Notas:</p>
                        {{form.notas}}
                    </div>

                    <div class="form-group">
                      <p> Mula:</p>
                        {{form.Mula}}
                    </div>
                    <!--Parrafo Error -->
                    <div class="form-group my-5 p-0">

                        <p class="parrafoError m-5"></p>   

                    </div>
            
            
            
                        <input type="submit"  class="btn btn-primary mr-5" style="width: 120px;">
                        
                       
                      </form>
        
        
        
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
    </div>
  </section>
  <!-- /.content -->
 
  <!-- ======= Modals ======= -->

 <!-- InfoGastoExtraModal -->
<div class="modal fade" id="InfoGastoExtraModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Gasto Extra</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
            
          
              <h3 class="profile-username text-center nombre"></h3>
          
           
              <ul class="list-group list-group-unbordered mb-3">
                
                <li class="list-group-item">
                  <b>Cantidad de Dinero:</b> <a class="float-right cant_dinero"></a>
                </li>

                <li class="list-group-item">
                  <b>Notas:</b>
                  <textarea cols="40" rows="10" maxlength="99999" class="form-control" readonly id="notas_modal"><a class="float-right cant_dinero"></a></textarea>
                </li>
              </ul>
          
            </div>
            <!-- /.card-body -->
            
          </div>
          
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Ok</button>
     
      </div>
    </div>
  </div>
</div>



{% endblock %}

{% block js_personalizado%}

<script> var url_ok= '{{url_ok}}';</script>

<!-- Mi Funcion Ajax -->
<script src="{% static 'Controlador/mis_js/crear_envio_ajax.js'%}"></script>

{% endblock %}

Apps/Controlador/templates/Controlador/Envios/crear_gasto_extra.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" >
        {% csrf_token %}
  
          {{form.as_p}}
           
          
            <input type="submit"  class="btn btn-primary mr-5" style="width: 120px;">
            
        </form>
</body>
</html>

Apps/Controlador/templates/Controlador/Envios/detail_envio.html
{% extends 'Controlador/base.html'%}

{% load static %}  
  

{% block contentPrincipal%}

<!-- Content Header (Page header) -->
<section class="content-header">
    
  </section>


 <div class="card card-primary m-5">

  <div class="card-header">
    <h3 class="card-title">Detalles de Envio</h3>
  </div>

  <!-- /.card-header -->
  <div class="card-body">
    <strong><i class="fas fa-book mr-1"></i> Nombre:</strong>

    <p class="text-muted ml-4">
      {{envio.Nombre}}
    </p>

    <hr>


    <!-- INVENTARIO -->
    <strong><i class="fas fa-pencil-alt mr-1"></i> Inventario:</strong>

    <div class="form-group mt-4" id="packs">
       
        <table id="listado_de_objetos" class="hover cell-border" style="width:100%">

            <thead>

                <tr>
                    <th scope="col" style="width: 35%; ">Nombre</th>
                    <th scope="col" style="width: 25%; ">Precio de Compra</th>
                    <th scope="col" style="width: 25%; ">Precio de venta</th>
                    <th scope="col" style="width: 14%; ">Cantidad</th>
                </tr>
            </thead>

        </table>
        
       
    </div>

    <hr>


    <!-- GASTOS EXTRAS -->
    <strong><i class="fas fa-pencil-alt mr-1"></i> Gastos Extras:</strong>

    <div class="form-group mt-4" id="gasto_extra">
        

        <table id="gastos_extras" class="hover cell-border" style="width:100%">

            <thead>

                <tr>
                    <th scope="col" style="width: 35%; ">Nombre</th>
                    <th scope="col" style="width: 25%; ">Cantidad</th>
                    <th scope="col" style="width: 25%; ">Detalles</th>
                </tr>
            </thead>

        </table>
       

    </div>

    <hr>

    <strong><i class="fas fa-map-marker-alt mr-1"></i> Fecha:</strong>

    <p class="text-muted ml-4">{{envio.Fecha}}</p>

    <hr>

    <strong><i class="fas fa-map-marker-alt mr-1"></i> Dinero Invertido:</strong>

    <p class="text-muted ml-4">{{envio.Dinero_Total_Invertido}}</p>

    <hr>

    <strong><i class="fas fa-pencil-alt mr-1"></i> Dinero Total Obtenido:</strong>

    <p class="text-muted ml-4">{{envio.Dinero_Total_obtenido}}
    </p>

    <hr>

    <strong><i class="fas fa-pencil-alt mr-1"></i> Ganancia:</strong>

    <p class="text-muted ml-4">{{envio.Ganancia}}
    </p>

    <hr>

    <strong><i class="fas fa-pencil-alt mr-1"></i> Mula:</strong>

    <p class="text-muted ml-4">{{envio.Mula}}
    </p>

    <hr>

    <strong><i class="fas fa-pencil-alt mr-1"></i> Notas:</strong>

    <p class="text-muted ml-4">{{envio.notas}}
    </p>

    <hr>


    

    

    




    

    <strong><i class="far fa-file-alt mr-1"></i> Opciones:</strong>

    <div class="row mt-3 mr-5" style="justify-content: center;" id="botones_de_opciones">

      <button type="button" rel='editar_envio' class="btn btn-primary mr-5" style="width: 120px;">Editar</button>
      <button type="button" rel='eliminar_envio'class="btn  btn-danger mr-5" style="width: 120px;">Eliminar</button>
      <a href="{{url_ok}}" rel="volver" class="btn btn-dark" style="width: 120px;">Volver</a>
    </div>
    
    
  </div>
  <!-- /.card-body -->
</div>

<!-- InfoGastoExtraModal -->
<div class="modal fade" id="InfoGastoExtraModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Gasto Extra</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
            
          
              <h3 class="profile-username text-center nombre"></h3>
          
           
              <ul class="list-group list-group-unbordered mb-3">
                
                <li class="list-group-item">
                  <b>Cantidad de Dinero:</b> <a class="float-right cant_dinero"></a>
                </li>

                <li class="list-group-item">
                  <b>Notas:</b>
                  <textarea cols="40" rows="10" maxlength="99999" class="form-control" readonly id="notas_modal"><a class="float-right cant_dinero"></a></textarea>
                </li>
              </ul>
          
            </div>
            <!-- /.card-body -->
            
          </div>
          
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Ok</button>
     
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js_personalizado%}

<script> var url_ok= '{{url_ok}}';</script>
<script> var token= '{{envio.pk}}';</script>
<!-- Mi Funcion Ajax -->
<script src="{% static 'Controlador/mis_js/detail_envio_ajax.js'%}"></script>

{% endblock %}

Apps/Controlador/templates/Controlador/Envios/lista_envios.html
{% extends 'Controlador/base.html'%}

{% load static %}  
  

{% block contentPrincipal%}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      
    </div><!-- /.container-fluid -->
  </section>





  
    <div class="card ml-4 mr-4 p-4">


        <div class="card-header mb-3" id="card_header"> 
            <h3 class="card-title" style="font-weight: bold;">Listado de Envios </h3>


            <div class="row" style="float: right;">

              <a href="{% url 'Controlador:crear_envio'%}" type="button" class="btn btn-success mr-3">Agregar Envio</a>

              <input type="button" class="btn btn-danger" rel='boton_eliminar'  id="contador" placeholder="Company" value="Eliminar">
            </div>
            

        </div>

        <table id="listado_de_envios" class="hover cell-border" style="width:100%">

            <thead>

                <tr>
                    <th scope="col" style="width: 1%; "><input rel='seleccionar_todo'  type='checkbox'/></th>
                    <th scope="col" style="width: 20%; ">Nombre</th>
                    <th scope="col" style="width: 20%; ">Cantidad Invertida</th>
                    <th scope="col" style="width: 20%; ">Cantidad Obtenida</th>
                    <th scope="col" style="width: 19%; ">Ganancia</th>
                    <th scope="col" style="width: 19%; ">Detalles</th>
                </tr>
            </thead>

        </table>
        <spam id="contador_de_envios">Envios Seleccionados: 0</spam>
        


    </div>


    
{% endblock %}




{% block js_personalizado%}






<script> var url_ok= '{{url_ok}}';</script>
<!-- Mi Funcion Ajax -->
<script src="{% static 'Controlador/mis_js/lista_envios_ajax.js'%}"></script>

{% endblock %}