Apps/Controlador/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = "Controlador"

urlpatterns = [
    
    path('', DashboardView.as_view(),name='dashboard'),

    ##### Mulas #####
    path('Lista_Mulas', ListaMulaView.as_view(),name='lista_de_mulas'),
    path('Editar_Mula/<str:pk>', EditarMulaView.as_view(),name='editar_mula'),
    path('Detail_Mula/<str:pk>', DetailMula.as_view(),name='detalles_mula'),

    ##### Objeto #####
    path('Lista_Objetos', ListaObjetosView.as_view(),name='lista_de_objetos'),
    

    ##### Gasto Extra #####
    path('Lista_Gastos_Extras', ListaGastosExtrasView.as_view(),name='lista_gastos_extra'),
    path('Crear_Gasto_Extra', CrearGastoExtraeView.as_view(),name='crear_gasto_extra'),

    ##### Envios #####
    path('Lista_Envios', ListaEnvioView.as_view(),name='lista_de_envios'),
    path('Crear_Envio', CrearEnvioView.as_view(),name='crear_envio'),
    path('Detail_Envio/<str:pk>', DetailEnvioView.as_view(),name='detalles_envio'),
    path('Editar_Envio/<str:pk>', EditarEnvioView.as_view(),name='editar_envio')
    
    #path('Prueba/', ArticleView.as_view(),name='prueba'),
]

Mula/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Apps.Controlador.urls')),


]

Apps/Controlador/forms.py
from dataclasses import field, fields
from django import forms
from .models import *
from django.forms import ModelForm
from datetime import datetime,timedelta,timezone

class MulaForm(ModelForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for i in self.visible_fields():
            i.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Mula
        fields =["Nombre","Telefono"]

        widgets = {

            'Nombre': forms.TextInput(attrs={
                'placeholder': 'Nombre',
                'autocomplete':'off'}),

            'Telefono': forms.NumberInput(attrs={
                'placeholder': 'Telefono',
                'autocomplete':'off'}),
                'min': 0,

            

        }
       


class EditarMulaForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for i in self.visible_fields():
            i.field.widget.attrs['class'] = 'form-control'


class EnvioForm(ModelForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for i in self.visible_fields():
            i.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Envio
        fields =["Nombre","Dinero_Total_Invertido","Gasto_total_en_pasajes","Dinero_Total_obtenido","Ganancia","notas","Fecha",'Mula']

        widgets = {

            'Nombre': forms.TextInput(attrs={
                'placeholder': 'Nombre',
                'autocomplete':'off'}),

            'Gasto_total_en_pasajes': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),
                'min': 0,

            'Dinero_Total_obtenido': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),
            
            'Dinero_Total_Invertido': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),

            'Ganancia': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),
            
            'Fecha': forms.DateInput(attrs={
                'placeholder': '',
                'autocomplete':'off'})

        }

    def clean(self):
        cleaned_data = super().clean()
        


class CrearObjetoForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for i in self.visible_fields():
            i.field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Objeto
        fields =["Nombre","PrecioDeCompra","PrecioDeVenta"]

        widgets = {

            'Nombre': forms.TextInput(attrs={
                'placeholder': 'Nombre',
                'autocomplete':'off'}),

            'PrecioDeCompra': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),

            'PrecioDeVenta': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),

        }

    def clean(self):
        cleaned_data = super().clean()     



class CrearGastoForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for i in self.visible_fields():
            i.field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Gasto_Extra
        fields =["Nombre","Cantidad_de_dinero","notas"]

        widgets = {

            'Nombre': forms.TextInput(attrs={
                'placeholder': 'Nombre',
                'autocomplete':'off'}),

            'Cantidad_de_dinero': forms.NumberInput(attrs={
                'placeholder': '',
                'autocomplete':'off'}),

            'notas': forms.Textarea(attrs={
                'placeholder': '',
                'autocomplete':'off'}),

        }

    def clean(self):
        cleaned_data = super().clean()     

    

Apps/Controlador/views.py
from django.views.generic import TemplateView,FormView,ListView,CreateView,DeleteView,DetailView
from .models import *
from .forms import *
from django.http import JsonResponse
from django.views.decorators.csrf  import csrf_exempt
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls  import reverse_lazy
from django.shortcuts import render,redirect
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
#funcion para obtener los packs de un envio
def getPacks(envio):
    data=[]

    inventario = envio.Inventario
                
    for i in Pack.objects.filter(Inventario=inventario):
        data.append(i)
    
    return data


#Funcion para eliminar una o varias mulas
def DeleteMulaFunction(data):

    datos_for_return =[]
    datos=[]
    #conviertes la data en una lista(ya que al venir esa data de un objeto json por ajax viene como str y hay que convertirla con el metodo split)
    lista= data.split(',')
    
    #Analizamos que la lista tenga algo, en caso de tenerlo lo eliminamos    
    if len(data) == 0:
        pass 
    else:
        for i in lista:
            mula = Mula.objects.get(pk=i)
            envios = Envio.objects.filter(Mula=mula)
            
            if envios:
                for k in envios:
                    datos.append(k)
            else:
                mula.delete()
            
            if datos:
                datos_for_return.append({'mula':mula.Nombre,'envios':datos})
                datos=[]
        
        return datos_for_return

    
    
#Funcion para eliminar uno o varios envios
def DeleteEnvioFunction(data):

    #conviertes la data en una lista(ya que al venir esa data de un objeto json por ajax viene como str y hay que convertirla con el metodo split)
    lista= data.split(',')
    
    #Analizamos que la lista tenga algo, en caso de tenerlo lo eliminamos    
    if len(data) == 0:
        pass 
    else:
        for i in lista:
            
            envio = Envio.objects.get(pk=i)
            
            inventario = Inventario.objects.get(pk=envio.Inventario.token)

            RestaroSumarViajeALaMula(False,envio.Mula)

        
            envio.delete()


            #eliminando el inventario asociado al envio
            inventario.delete()
            

#Funcion para eliminar uno o varios objetos
def DeleteObjetoFunction(data):

    #conviertes la data en una lista(ya que al venir esa data de un objeto json por ajax viene como str y hay que convertirla con el metodo split)
    lista= data.split(',')
    
    datos=[]
    datos_for_return=[]
    #Analizamos que la lista tenga algo, en caso de tenerlo lo eliminamos    
    if len(data) == 0:
        pass 
    else:
        for i in lista:
            
            #En este ciclo analizamos que los objetos que fueron seleccionados para eliminar no esten asociados a ningun envio
            #Si estan asociados a alguno pues no eliminamos y lo informamos para que el usuario tome las acciones pertinentes 
            obj = Objeto.objects.get(pk=i)
            
            pack = Pack.objects.filter(objeto=obj)

            

            for k in pack:
                x = Envio.objects.get(Inventario=k.Inventario)
                datos.append(x)
            
            if datos:
                datos_for_return.append({'objeto':obj.Nombre,'envios':datos})
                datos=[]
            else:
                obj.delete()
                

        
            if datos_for_return:
              
                return datos_for_return
                
  
            else:
                return False




def RestaroSumarViajeALaMula(restar_o_sumar,mula):
    mula = mula
    if restar_o_sumar:
        
        mula.CantidadDeEnviosRealizados += 1
        
    else:
        mula.CantidadDeEnviosRealizados -= 1
    
    mula.save()

    



def procesar_datos(data,tipo,estado):
    
    data_return=[]
    #Aqui los meto dentro de una lista de python especificando que donde quiera que vea un ' ,' es un elemento nuevo
    #El espacio antes de la coma es porque como son diccionarios puede haber muchas comas 
    #entonces configure que me enviara los elementos con un espaciado por medio para poder identificar 
    #que , es la de dentro de un diccionario y que , es la que divide un elemento de otro
    lista= data.split(' ,')
    listaDict=[]

    #Aqui convierto los diccionarios que vienen en str en dicts de python para poder acceder a sus datos
    for j in lista:
        listaDict.append(json.loads(j))



        #si estado == true hacemos referencia que estamos cerrando el registro (de inventario o gastos extras)
        #si estado == false hacemos referencia que estamos abriendo el registro (de inventario o gastos extras)

        # si tipo == true hacemos referencia al trabajo con el inventario
        # si tipo == false hacemos referencia al trabajo con los gastos extras


    if estado:


        #ESTADO = TRUE TIPO = TRUE, CERRANDO INVENTARIO
        if tipo:
            for j in listaDict:
                for i in Objeto.objects.filter(token = j["token"]).values():
                    i['cantidad']=j["cantidad"]
                    i['listo']=True
                    #Pack.objects.create(objeto_id=i['token'],Cantidad_de_ejemplares=i['cantidad'])
                    data_return.append(i)
        
        #ESTADO = TRUE TIPO = FALSE, CERRANDO GASTOS EXTRAS
        else:

            for j in listaDict:
                for i in Gasto_Extra.objects.filter(token = j["token"]).values():
                    i['listo']=True
                    data_return.append(i)
    

    else:

        #ESTADO = FALSE TIPO = TRUE, ABRIENDO INVENTARIO    
        if tipo:

                datos_que_se_encontraban_seleccionados=[]

                for j in listaDict:
                    for i in Objeto.objects.filter(token = j["token"]).values():
                            i['cantidad']=j["cantidad"]
                            i['listo']=False
                            datos_que_se_encontraban_seleccionados.append(i)


                

                todos=[]
                for i in Objeto.objects.all().values():
                    todos.append(i)

                
                for i in todos:
                    for k in datos_que_se_encontraban_seleccionados:
                        if i["token"]==k["token"]:                                                       
                            i['cantidad']=k["cantidad"]
                            i['listo']=False

                data_return=todos
        
        #ESTADO = FALSE TIPO = FALSE, ABRIENDO GASTOS EXTRAS
        else:

            datos_que_se_encontraban_seleccionados=[]

            for j in listaDict:
                for i in Gasto_Extra.objects.filter(token = j["token"]).values():
                        i['cantidad']=j["cantidad"]
                        i['listo']=False
                        datos_que_se_encontraban_seleccionados.append(i)


            

            todos=[]
            for i in Gasto_Extra.objects.all().values():
                todos.append(i)

            
            for i in todos:
                for k in datos_que_se_encontraban_seleccionados:
                    if i["token"]==k["token"]:                                                       
                        i['cantidad']='0'
                        i['listo']=False

            data_return=todos



    return data_return





#Vista Index
class IndexdView (TemplateView):
    template_name= 'Controlador/index.html'


#Vista principal
class DashboardView (TemplateView):
    template_name= 'Controlador/dashboard.html' 

    def get_dinero_mensual(self):
        data=[]
        suma_total=0
        year = datetime.now().year

        for m in range(1,13):
            total = Envio.objects.filter(Fecha__year=year,Fecha__month=m)
            data.append(total)
       
        
        for i in range(0,len(data)):
            if data[i]:
                for k in data[i]:
                    suma_total += k.Ganancia
                data[i]= suma_total
                suma_total=0

            else:
                data[i]=0
            

        return data

    def get_cantidad_total_de_envios(self):
        datos = Envio.objects.all()
        data = len(datos)
        return data

    def get_cantidad_total_de_mulas(self):
        datos = Mula.objects.all()
        data = len(datos)
        return data

    def get_cantidad_total_de_ganancia(self):
        datos = Envio.objects.all()
        ganancia_total =0
        if datos:
            for i in datos:
                ganancia_total += i.Ganancia
      
        return ganancia_total

    def get_cantidad_total_de_inversion(self):
        datos = Envio.objects.all()
        inversion_total =0
        if datos:
            for i in datos:
                inversion_total += i.Dinero_Total_Invertido
      
        return inversion_total

            


    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['x']=self.get_dinero_mensual()
        context['cant_envios']=self.get_cantidad_total_de_envios()
        context['cant_mulas']=self.get_cantidad_total_de_mulas()
        context['cant_ganancia']=self.get_cantidad_total_de_ganancia()
        context['cant_invertida']=self.get_cantidad_total_de_inversion()
        
        return context














####### MULAS #######

#Vista que muestra nuestra lista de mulas y las opciones correspondientes con estas
class ListaMulaView (ListView):
    template_name= 'Controlador/Mulas/lista_mulas.html'  
    model = Mula
    context_object_name="lista_mulas"

    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['form']=MulaForm()
        return context

Apps/Controlador/templates/Controlador/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mula</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'Controlador/plugins/fontawesome-free/css/all.min.css'   %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'Controlador/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'   %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'Controlador/dist/css/adminlte.min.css'   %}">

  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
 





  <!-- Datatable-->
  <link rel="stylesheet" type="text/css" href="{% static 'Controlador/data_tables/datatables.min.css' %}"/>

  <!-- Iconos Bootstrap-->
  <link rel="stylesheet" type="text/css" href="{% static 'Controlador/iconos_bootstrap/font/bootstrap-icons.css' %}"/>

  <!-- Desactivar el step de los number fiedl-->
  <link rel="stylesheet" type="text/css" href="{% static 'Controlador/mis_css/desactivar_step_numberfield.css' %}"/>

  <!-- Sweet Alert -->
  <link rel="stylesheet" href="{% static 'Controlador/plugins/sweetalert2/sweetalert2.min.css'   %}">

  <!-- Jquery Confirm CSS Files -->
  <link rel="stylesheet" href="{% static 'Controlador/plugins/Jquery-confirm/dist/jquery-confirm.min.css'%}">

  
</head>


<body class="hold-transition sidebar-mini layout-fixed">

    
<!-- Site wrapper -->
<div class="wrapper">
 
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
   
    </ul>

    
   
     
    
        
  </nav>

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src="{% static 'Controlador/dist/img/AdminLTELogo.png'   %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Mula</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'Controlador/dist/img/user2-160x160.jpg'   %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{user}}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

          <li class="nav-item">

            <a href="{% url 'Controlador:dashboard'%}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard  
              </p>
            </a>
        
          </li>

          

          <!-- Mula Menu -->
          <li class="nav-item ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Mulas
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              <li class="nav-item">
                <a href="{% url 'Controlador:lista_de_mulas'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Lista de Mulas</p>
                </a>
              </li>
             
            
            </ul>
          </li>

          <!-- Envio Menu -->
          <li class="nav-item ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Envios
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              <li class="nav-item">
                <a href="{% url 'Controlador:lista_de_envios'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Lista de Envios</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'Controlador:crear_envio'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Crear Envio</p>
                </a>
              </li>
            
            </ul>
          </li>

          <!-- Objeto Menu -->
          <li class="nav-item ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Objetos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              <li class="nav-item">
                <a href="{% url 'Controlador:lista_de_objetos'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Lista de Objetos</p>
                </a>
              </li>
           
            
            </ul>
          </li>


          <!-- Gasto Extra Menu -->
          <li class="nav-item ">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Gasto Extra
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              <li class="nav-item">
                <a href="{% url 'Controlador:lista_gastos_extra'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Lista de Gastos Extras</p>
                </a>
              </li>
           
            
            </ul>
          </li>

          

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    
    {% block contentPrincipal%}
  
  

    {% endblock %}
   
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.2.0
    </div>
    <strong>Copyright &copy; <a href="#">Mula.io</a></strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'Controlador/plugins/jquery/jquery.min.js'   %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'Controlador/plugins/bootstrap/js/bootstrap.bundle.min.js'   %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'Controlador/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'   %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'Controlador/dist/js/adminlte.min.js'   %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'Controlador/dist/js/demo.js'   %}"></script>
<!-- Datatable-->
<script type="text/javascript" src="{% static 'Controlador/data_tables/datatables.min.js' %}"></script>
<!-- Sweet Alert -->
<script type="text/javascript" src="{% static 'Controlador/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Controlador/plugins/sweetalert_Mio/sweetaler2.js' %}"></script>
<!-- Jquery Confirm JS Files -->
<script src="{% static 'Controlador/plugins/Jquery-confirm/dist/jquery-confirm.min.js'%}"></script>


<!-- Mi Funcion Ajax -->
<script src="{% static 'Controlador/mis_js/ajax.js'%}"></script>


{% block js_personalizado%}

{% endblock %}

</body>
</html>

Apps/Controlador/templates/Controlador/dashboard.html
{% extends 'Controlador/base.html'%}

{% load static %}  
  

{% block contentPrincipal%}

<div class="container p-5">

    <div class="row">

        
          
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-info">
            <div class="inner">
              <h3>{{cant_envios}}</h3>
    
              <p>Envios</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-warning">
            <div class="inner">
              <h3>{{cant_mulas}}</h3>
              
    
              <p>Mulas</p>
            </div>
            <div class="icon">
              <i class="ion ion-person"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-success">
            <div class="inner">
              <h3>{{cant_ganancia}}</h3>
    
              <p>Ganancia Total</p>
            </div>
            <div class="icon">
              <i class="ion ion-cash"></i>
            </div>
            
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-danger">
            <div class="inner">
              <h3>{{cant_invertida}}</h3>
    
              <p>Inversion Total</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
      </div>
     
    <div class="row justify-content-md-center mt-5">
        <div id="container" style="width: 800px;height: 400px"></div>
    </div>  
    
    
</div>



<script src="{% static 'Controlador/plugins/HighCharts/highcharts.js' %}"></script>
<script src="{% static 'Controlador/plugins/HighCharts/modules/exporting.js' %}"></script>
<script src="{% static 'Controlador/plugins/HighCharts/modules/export-data.js' %}"></script>
<script src="{% static 'Controlador/plugins/HighCharts/modules/accessibility.js' %}"></script>

<script>
    
    //var myJSON= '{{x}}';
    var datos= JSON.parse("{{x}}");



   
    

    Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Reporte de Ganancias del año 2022'
    },
    subtitle: {
        text: 'Ganancias Total de Cada Mes'
    },
    xAxis: {
        categories: [
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Ganancia en Dolares'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} $</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{
        name: 'Ganancia',
        showInLegend: false,
        data:  datos

    },]
});
</script>
{% endblock %}

Apps/Controlador/templates/Controlador/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" >
        {% csrf_token %}
  
          {{form.as_p}}
           
          
            <input type="submit"  class="btn btn-primary mr-5" style="width: 120px;">
            
        </form>
        
</body>
</html>